### ISSUE TITLE
Where can I find an adress you can buy the version 3 diy kit? Or the electronics scheme of version 3?

### ISSUE THREAD

**Issue by maarthome** [TreeFallSound/pi-stomp#100]
Hi incredible developers,

Where can I find the adress where you can buy the version 3 diy kit? 
And where can I find the electronics scheme of version 3?

Thanks for your GREAT pistomp device!!

Cheers,
Maarten

**Comment by rreichenbach** [comment]
v3 kits aren't available yet (as of Nov 2, 2024)

Go here for the latest news:
https://www.treefallsound.com/news/
