### ISSUE TITLE
IQaudio Codec Zero only build

### ISSUE THREAD

**Issue by Klinenator** [TreeFallSound/pi-stomp#101]
Is it possible to get this working with the IQaudio Codec Zero only? And use the web UI for everything else?

**Comment by rreichenbach** [comment]
Maybe expand more on what you mean by get THIS working.  If you mean you just want a MOD platform for audio, without any of the control features that pi-Stomp hardware and software allow, sure.  There may be a simpler solution out there, but pi-stomp does round up the pieces you need, so it might get you up and running quicker.

Pretty easy to just burn this beta build to an SD card and go:
https://github.com/treefallsound/pi-stomp/releases/

Since you don't have a display, you might want to disable/stop the main pi-stomp service so it's not eating up cpu cycles:
sudo systemctl disable --now mod-ala-pi-stomp

**Comment by Klinenator** [comment]
Well i wanted to buy a kit but theyre sold out. I was able to get a IQaudio Codec Zero online and am trying to use my Raspberry pi 5. I kept getting jack errors but didnt want to try any more without knowing its possible and that the lack of the kit was causing issues

**Comment by Klinenator** [comment]
I keep getting the error ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for MODDUO

Even though im using the IQaudio Codec Zero

And Jack is giving me these errors

Oct 31 23:17:31 pistomp jackd[1627]: Driver is not running
Oct 31 23:17:31 pistomp jackd[1627]: Cannot create new client
Oct 31 23:17:31 pistomp jackd[1627]: ALSA: poll time out, polled for 1999030 usecs, Retrying with a recovery, retry cnt = 3
Oct 31 23:17:35 pistomp jackd[1627]: ALSA: poll time out, polled for 1999017 usecs, Retrying with a recovery, retry cnt = 4
Oct 31 23:17:36 pistomp jackd[1627]: JackPosixProcessSync::LockedTimedWait error usec = 5000000 err = Connection timed out
Oct 31 23:17:36 pistomp jackd[1627]: Driver is not running
Oct 31 23:17:36 pistomp jackd[1627]: Cannot create new client
Oct 31 23:17:36 pistomp jackd[1627]: Cannot write socket fd = 17 err = Broken pipe
Oct 31 23:17:36 pistomp jackd[1627]: CheckRes error
Oct 31 23:17:36 pistomp jackd[1627]: JackRequest::ClientOpen write error name = mod-ui

**Comment by rreichenbach** [comment]
Make sure you get this output from this command:
`aplay -l`
**** List of PLAYBACK Hardware Devices ****
card 0: IQaudIOCODEC [IQaudIOCODEC], device 0: IQaudIO CODEC HiFi v1.2 da7213-hifi-0 [IQaudIO CODEC HiFi v1.2 da7213-hifi-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

It should be card 0.  If that all looks good, it would be worth checking for system errors by running:
`dmesg`

**Comment by Klinenator** [comment]
My output for aplay -l is

**** List of PLAYBACK Hardware Devices ****
card 0: IQaudIOCODEC [IQaudIOCODEC], device 0: IQaudIO CODEC HiFi v1.2
da7213-hifi-0 [IQaudIO CODEC HiFi v1.2 da7213-hifi-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM
i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM
i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by Klinenator** [comment]
I dont see any errors in dmesg

**Comment by Klinenator** [comment]
Also i discovered The Makefiles for mod-host and mod-ui are not working

-Bsymbolic needs to be added to both for LDFLAGS

**Comment by rreichenbach** [comment]
If you're building your own, then you're on you own.  I gave you a link earlier for a prebuilt image:
https://github.com/treefallsound/pi-stomp/releases/

Use that and I'm near certain, you'll have a working system within 20 minutes.

**Comment by Klinenator** [comment]
Oh perfect, I didn’t see that. Thank you

**Comment by Klinenator** [comment]
You were 100% correct. Loaded the image and was up and running immediately

Thank you

**Comment by rreichenbach** [comment]
Cheers!  Closing issue
