### ISSUE TITLE
Effect's parameter list

### ISSUE THREAD

**Issue by MacFizz** [TreeFallSound/pi-stomp#11]
When an effect has greater than 9 parameters, you can't access them because the screen doesn't scroll (or change page).
You can still select the parameter, but you can't see what parameter you're on until you've clicked on it.

The screen view would need to scroll or to display a new page of parameters.

**Comment by rreichenbach** [comment]
The original pi-Stomp does scroll the list but that has not been so easy to implement for the ili3941 display which renders differently.  Definitely possible though and will be fixed eventually.

**Comment by rreichenbach** [comment]
Fixed via commit: a0ce5e81d431bd1d360562d64a50932e94bada9d
