### ISSUE TITLE
Changing state of boolean parameters

### ISSUE THREAD

**Issue by MacFizz** [TreeFallSound/pi-stomp#12]
On the pi-stomp, when selecting a parameter of en effect that is boolean (like enable/disable), the parameter is shown as a 0 to 1 gradient and you need to turn the encoder a number of times to switch to on e status to the other.
It makes it very long to change.

**Comment by rreichenbach** [comment]
fixed via commit: d431a97dd06c8c107074d3ee4ec86f794016fc20 

Available in [beta-bookworm-dev](https://github.com/TreeFallSound/pi-stomp/tree/beta-bookworm-dev) branch, [v2.3.0-beta.1](https://github.com/TreeFallSound/pi-stomp/releases/tag/v2.3.0-beta.1) tag

**Comment by rreichenbach** [comment]
Note that the fix above is for v2 and v3 hardware.
