### ISSUE TITLE
Manual apt update and upgrade needed before install

### ISSUE THREAD

**Issue by MacFizz** [TreeFallSound/pi-stomp#13]
A repository's status has changed and now requires to be manually validated to update properly.
I'm not and apt expert so I have no idea if this can be somehow automated.
Upgrade seems to be necessary now, a few packages failed to install.
After upgrade, everything works.

**Comment by rreichenbach** [comment]
Thanks for pointing this out.

Commit 87c3a1c8a3845d94fb75cb63c4a75c59cd12fbb6 added ' sudo apt update -y --fix-missing' to setup.sh

At this point, I'd rather not run 'apt upgrade' unless absolutely necessary, and I don't believe it is.   I've confirmed with two from scratch builds which completed without issue.
