### ISSUE TITLE
MIDI learn only working for existing pedalboards

### ISSUE THREAD

**Issue by MarnixMeersman** [TreeFallSound/pi-stomp#57]
Hi,

I have a problem where I can only assign potentiometers and switches via MIDI-learn when I'm in the pedalboards that came with the installation. If I make a new pedalboards and save it on my pistomp, (I verified it was saved since I could play through it without the pi connected to WiFi) I'm unable to assign any midi control. 

I went through every option in the troubleshooting guide on the tree fall sound website. Nothing worked. 

Hoping someone can help. 

Cheers Marnix

**Comment by rreichenbach** [comment]
It sounds like your new pedalboard has the MIDI mode set to Aggregated.  For MIDI learn to work, it should be set to Segregated.

See this tutorial on how to change modes:
https://treefallsound.com/wiki/doku.php?id=tutorials_and_videos#controlling_pi-stomp

It's possible that the latest version of MOD has changed the default mode to be Aggregated.  I'll need to investigate.  Until then, try the manual mode change.

**Comment by MarnixMeersman** [comment]
Thanks, that was indeed the problem. Very happy with my pistomp. As promised over email, a picture of my build (will still get a paintjob). 
![pistomp](https://user-images.githubusercontent.com/57674797/223118516-95524e5f-bcef-4150-b1d3-61d6bd193cc2.jpg)

**Comment by rreichenbach** [comment]
Wow, awesome!  That's one maxxed out pi-Stomp!  Please share on the forum!  (https://treefallsound.com/forum)

**Comment by micahvdm** [comment]
MIDI mapping is fixed with the latest PR. Please do a full reinstall to fix!
