### ISSUE TITLE
Start page doesnt tell you Patchbox WiFi password

### ISSUE THREAD

**Issue by KevWal** [TreeFallSound/pi-stomp#6]
Hi

This page here:

https://www.treefallsound.com/wiki/doku.php?id=start#building_pi_stomp

Currently says 
"
After about a minute, the green LED should be flashing less frequently. At that point, you should be able to turn-on or redirect the wifi on your computer and connect to the Patchbox hotspot named: Patchbox
Once wifi is established, invoke your SSH client to connect to the pi:
"
It doesnt tell you that the WiFi password for the Patchbox SSID is "blokaslabs" :)

Cheers
Kev

**Comment by rreichenbach** [comment]
Fixed in wiki.  Thanks.
