### ISSUE TITLE
BETA Bypass not switching

### ISSUE THREAD

**Issue by JustBKen** [TreeFallSound/pi-stomp#87]
when attempting to toggle bypass through encoder (sselect Processing indicator, press encoder switch) pistomp fails to change state. Neither display nor relay change.

**Comment by rreichenbach** [comment]
Not a bug, just not implemented for the new LCD UI yet.  The beta branch is a development branch, not intended for general use.  A few other things not quite working yet:

- VU/Clipping Led’s.  Very jittery and not calibrated yet
- Wifi config via LCD not complete
- Knob assignments not showing yet
- LCD footswitch status doesn't refresh when snapshot is changed

**Comment by rreichenbach** [comment]
Bypass toggling was implemented via commit fac70e2
